<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="DSLSpecificCoverage" nsURI="https://org.imt.tdl.coverage/DSLSpecificCoverage"
    nsPrefix="DSLSpecificCoverage">
  <eClassifiers xsi:type="ecore:EClass" name="DomainSpecificCoverage">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="metamodel" lowerBound="1"
        eType="ecore:EClass ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EPackage"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="contexts" lowerBound="1"
        upperBound="-1" eType="#//Context" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="imports" upperBound="-1"
        eType="#//Import" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Import">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="importedNamespace" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="importURI" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="importedRuleset" eType="#//DomainSpecificCoverage"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Context">
    <eStructuralFeatures xsi:type="ecore:EReference" name="metaclass" lowerBound="1"
        eType="ecore:EClass ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EClass"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rules" lowerBound="1" upperBound="-1"
        eType="#//Rule" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Rule" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="condition" eType="#//Condition"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InclusionRule" abstract="true" eSuperTypes="#//Rule"/>
  <eClassifiers xsi:type="ecore:EClass" name="ExclusionRule" abstract="true" eSuperTypes="#//Rule"/>
  <eClassifiers xsi:type="ecore:EClass" name="CoverageOfReferenced" eSuperTypes="#//InclusionRule">
    <eStructuralFeatures xsi:type="ecore:EReference" name="reference" lowerBound="1"
        upperBound="-1" eType="ecore:EClass ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EReference"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CoverageByContent" eSuperTypes="#//InclusionRule">
    <eStructuralFeatures xsi:type="ecore:EReference" name="containmentReference" eType="ecore:EClass ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EReference"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="multiplicity" lowerBound="1"
        eType="#//CoveredContents"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Ignore" eSuperTypes="#//ExclusionRule">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ignoreSubtypes" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LimitedIgnore" eSuperTypes="#//ExclusionRule">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" lowerBound="1" eType="#//LimitationType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="containerMetaclass" lowerBound="1"
        upperBound="-1" eType="ecore:EClass ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EClass"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BranchSpecification" eSuperTypes="#//Rule">
    <eStructuralFeatures xsi:type="ecore:EReference" name="branches" lowerBound="1"
        upperBound="-1" eType="#//Branch" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExplicitBranch" eSuperTypes="#//Branch">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="OCLQuery" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Condition">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="OCLConstraint" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="CoveredContents">
    <eLiterals name="ALL"/>
    <eLiterals name="ONE" value="1"/>
    <eLiterals name="ANY" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="LimitationType">
    <eLiterals name="containedBy" literal="ContainedBy"/>
    <eLiterals name="notContainedBy" value="1" literal="NotContainedBy"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ImplicitBranch" eSuperTypes="#//Branch"/>
  <eClassifiers xsi:type="ecore:EClass" name="Branch" abstract="true"/>
</ecore:EPackage>
