/*
 * generated by Xtext 2.27.0
 */
package org.imt.tdl.amplification.dsl.xtext.ide;


/**
 * Use this class to register ide components.
 */
public class AmplifierIdeModule extends AbstractAmplifierIdeModule {
}
