<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="amplifier" nsURI="http://org.imt.tdl.amplification/configuration/amplifier"
    nsPrefix="amplifier">
  <eClassifiers xsi:type="ecore:EClass" name="Configuration">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="metamodel" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EPackage"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="behavioralInterfaceUri"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="approach" lowerBound="1"
        eType="#//AmplificationApproach" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="operators" lowerBound="1"
        upperBound="-1" eType="#//TestModificationOperator" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="filtering" lowerBound="1"
        eType="#//TestSelectionCriterion" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AmplificationApproach" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="selectionScoreThreshold"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Iterative" eSuperTypes="#//AmplificationApproach">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="numOfIterations" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SearchBased" eSuperTypes="#//AmplificationApproach"/>
  <eClassifiers xsi:type="ecore:EClass" name="TestModificationOperator" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="policy" lowerBound="1"
        eType="#//ApplicationPolicy"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="maxOccurrence" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ApplicationPolicy">
    <eLiterals name="all" value="1"/>
    <eLiterals name="one" value="2"/>
    <eLiterals name="each" value="3" literal="each"/>
    <eLiterals name="first" value="4"/>
    <eLiterals name="last" value="5"/>
    <eLiterals name="fixed" value="6"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PrimitiveDataModifier" eSuperTypes="#//TestModificationOperator"/>
  <eClassifiers xsi:type="ecore:EClass" name="NumericValueModifier" eSuperTypes="#//PrimitiveDataModifier"/>
  <eClassifiers xsi:type="ecore:EClass" name="StringValueModifier" eSuperTypes="#//PrimitiveDataModifier"/>
  <eClassifiers xsi:type="ecore:EClass" name="BooleanValueModifier" eSuperTypes="#//PrimitiveDataModifier"/>
  <eClassifiers xsi:type="ecore:EClass" name="EventSequenceModifier" eSuperTypes="#//TestModificationOperator">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="scope" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EventDuplication" eSuperTypes="#//EventSequenceModifier"/>
  <eClassifiers xsi:type="ecore:EClass" name="EventDeletion" eSuperTypes="#//EventSequenceModifier"/>
  <eClassifiers xsi:type="ecore:EClass" name="EventPermutation" eSuperTypes="#//EventSequenceModifier"/>
  <eClassifiers xsi:type="ecore:EClass" name="EventCreation" eSuperTypes="#//EventSequenceModifier"/>
  <eClassifiers xsi:type="ecore:EClass" name="EventModification" eSuperTypes="#//EventSequenceModifier"/>
  <eClassifiers xsi:type="ecore:EClass" name="TestSelectionCriterion" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="ElementCoverage" eSuperTypes="#//TestSelectionCriterion"/>
  <eClassifiers xsi:type="ecore:EClass" name="MutationAnalysis" eSuperTypes="#//TestSelectionCriterion">
    <eStructuralFeatures xsi:type="ecore:EReference" name="mutationOperators" eType="#//MutationOperator"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MutationOperator" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="pathToMutationOperatorsFile"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UserDefinedOperator" eSuperTypes="#//MutationOperator"/>
  <eClassifiers xsi:type="ecore:EClass" name="GeneratedOperator" eSuperTypes="#//MutationOperator">
    <eStructuralFeatures xsi:type="ecore:EReference" name="operatorsTypes" lowerBound="1"
        upperBound="-1" eType="#//MutationOperatorType" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MutationOperatorType" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="scope" upperBound="-1"
        eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EClass"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CreationOperator" eSuperTypes="#//MutationOperatorType"/>
  <eClassifiers xsi:type="ecore:EClass" name="CloningOperator" eSuperTypes="#//MutationOperatorType"/>
  <eClassifiers xsi:type="ecore:EClass" name="RemovalOperator" eSuperTypes="#//MutationOperatorType"/>
  <eClassifiers xsi:type="ecore:EClass" name="ModificationOperator" eSuperTypes="#//MutationOperatorType"/>
  <eClassifiers xsi:type="ecore:EClass" name="RetypingOperator" eSuperTypes="#//MutationOperatorType"/>
</ecore:EPackage>
