/*
 * generated by Xtext 2.27.0
 */
package org.imt.tdl.amplification.dsl.xtext.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class AmplifierUiModule extends AbstractAmplifierUiModule {

	public AmplifierUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
