/*
 * generated by Xtext 2.27.0
 */
package org.imt.tdl.amplification.dsl.xtext;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class AmplifierStandaloneSetup extends AmplifierStandaloneSetupGenerated {

	public static void doSetup() {
		new AmplifierStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
