/*
 * generated by Xtext 2.27.0
 */
package org.imt.tdl.amplification.dsl.xtext;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class AmplifierRuntimeModule extends AbstractAmplifierRuntimeModule {
}
